version: "3"
services:
    core:
        image: "tokland/dhis2-core:2.30"
        labels:
            - "com.eyeseetea.image-name=${DHIS2_DATA_IMAGE}"
        volumes:
            - ./config/DHIS2_home/dhis.conf:/DHIS2_home/dhis.conf
            - ./config/server.xml:/usr/local/tomcat/conf/server.xml
            - home:/DHIS2_home
            - data:/DHIS2_home/files/
        environment:
            CATALINA_OPTS: "-Dcontext.path='${DHIS2_CORE_CONTEXT_PATH:-}'"
        depends_on:
            - "db"
    db:
        image: "tokland/postgis:10-alpine"
        command: "postgres -c max_locks_per_transaction=100"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - data:/data
        environment:
            POSTGRES_DB: dhis2
            POSTGRES_USER: dhis
            POSTGRES_PASSWORD: dhis
        depends_on:
            - "data"
    gateway:
        image: "jwilder/nginx-proxy:alpine"
        ports:
            - "${DHIS2_CORE_PORT:-8080}:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
    data:
        image: "${DHIS2_DATA_IMAGE}"
        environment:
            VOLUME: /volume-data
        volumes:
            - data:/volume-data

volumes:
    pgdata:
    home:
    data:
